### ISSUE TITLE
Please update the KM Javascript Snippet (Accept my pull request)

### ISSUE THREAD

**Issue by williamrmyers** [angulartics/angulartics-kissmetrics#4]
Hi Guys,

I am a Kissmetrics Employee. I have pushed an update to the Kissmetrics Javascript Snippet. I would like to get it accepted so I can link Angulartics in our Documentation.

Thanks!
William

**Comment by timelf123** [comment]
Merged, thanks for the PR!

**Comment by williamrmyers** [comment]
Hey Anytime! I just pushed another update, this time to update the angulartics version number  in package.json so the package is no longer tagged as **out-of-date** by GitHub.
