### ISSUE TITLE
Using angulartics Version .2 and is tagged as out-of-date

### ISSUE THREAD

**Issue by williamrmyers** [angulartics/angulartics-kissmetrics#5]
Hey again guys!

I just pushed another update, this time to update the angulartics version number in **package.json** so the package is no longer tagged as **out-of-date** by GitHub.

Please except it, or let me know if there a reason this should not be updated to the newest version.

Thanks a lot.
William

**Comment by timelf123** [comment]
Hi @williamrmyers did you mean to submit a PR?

**Comment by timelf123** [comment]
https://github.com/angulartics/angulartics-kissmetrics/releases/tag/0.2.0
